# Rust needs at least Visual Studio 2013 Appveyor OS for MSVC targets.
os: Visual Studio 2017

# disable .net
build: false

environment:
  # When this was added there were revocation check failures when using the
  # libcurl backend as libcurl checks by default, but rustup doesn't provide the
  # switch to turn this off. Switch to Hyper which looks to not check for
  # revocation by default like libcurl does.
  RUSTUP_USE_HYPER: 1
  CARGO_HTTP_CHECK_REVOKE: false
  matrix:
  - TARGET: x86_64-pc-windows-gnu
    MSYS2_BITS: 64
  - TARGET: x86_64-pc-windows-msvc

install:
  - appveyor-retry appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init.exe -y --default-host %TARGET%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - if defined MSYS2_BITS set PATH=%PATH%;C:\msys64\mingw%MSYS2_BITS%\bin
  - rustc -V
  - cargo -V
  - git clone --branch pthread_setname https://github.com/dns2utf8/libc.git ../libc

test_script:
  - cargo run --target %TARGET%
